export const SAMY_WORD_DATABASE = [
    { word: 'Air', type: 'ai', clue: 'The clean, invisible gas that wraps all around the Earth for us to breathe.', sentence: 'The crisp cool ___ felt lovely on my face during our walk.', frequency: 'core' },
    { word: 'Aim', type: 'ai', clue: 'To carefully point a toy arrow, camera, or game dart towards the target.', sentence: 'Close one eye, focus, and take your ___ at the yellow balloon.', frequency: 'core' },
    { word: 'Snail', type: 'ai', clue: 'A slow-moving gardener friend carrying a beautiful spiral shell on its back.', sentence: 'Samy the garden ___ left a shiny, glittery trail on the green leaf.', frequency: 'core' },
    { word: 'Straight', type: 'ai', clue: 'Moving directly in one path without bending, curving, or wiggling.', sentence: 'Use a clean wooden ruler to draw a perfectly ___ line.', frequency: 'core' },
    { word: 'Brain', type: 'ai', clue: 'The wonderful, powerful thinking center inside your head.', sentence: 'Reading helps exercise your clever ___ and makes you smarter.', frequency: 'core' },
    { word: 'Rain', type: 'ai', clue: 'Fresh water droplets falling all the way down from gray storm clouds.', sentence: "Let's put on colorful boots and jump in the wet puddles of ___.", frequency: 'core' },
    { word: 'Paint', type: 'ai', clue: 'A colorful, slick liquid that artists brush onto papers and walls.', sentence: 'We can mix yellow and blue ___ together to create grass-green.', frequency: 'core' },
    { word: 'Pair', type: 'ai', clue: 'A set of two things matching or meant to go together (like clean socks).', sentence: 'Grandpa bought a warm, comfy new ___ of wool slippers.', frequency: 'core' },
    { word: 'Main', type: 'ai', clue: 'The most important, leading, or biggest part of something.', sentence: 'The hero had to overcome the ___ challenge in the fairy tale.', frequency: 'core' },
    { word: 'Afraid', type: 'ai', clue: 'Feeling a bit scared, nervous, or frightened of something.', sentence: 'The brave puppy was not ___ of the giant squeaky vacuum.', frequency: 'core' },
    { word: 'Stair', type: 'ai', clue: 'A single steps to walk upwards or downwards to another floor.', sentence: 'Carefully place your foot on each wooden ___ as you climb.', frequency: 'core' },
    { word: 'Chair', type: 'ai', clue: 'A piece of furniture with a flat back and seat designed for one person.', sentence: 'Sit comfortably in the soft blue ___ at the reading corner.', frequency: 'core' },
    { word: 'Away', type: 'ay', clue: 'Moving to a different location or leaving the current place.', sentence: 'The red robin spread its wings and flew far ___ into the sky.', frequency: 'core' },
    { word: 'Clay', type: 'ay', clue: 'A thick, earthy mud that is fun to squeeze, mold, and sculpt.', sentence: 'We molded a small, shiny bowl out of sticky green ___.', frequency: 'core' },
    { word: 'Say', type: 'ay', clue: 'To speak words out loud using your voice.', sentence: 'What polite words should you ___ when someone gives you a gift?', frequency: 'core' },
    { word: 'Stray', type: 'ay', clue: 'An animal that is lost or wandering without a home.', sentence: 'The kind veterinarian fed and rescued a friendly ___ kitten.', frequency: 'core' },
    { word: 'Tray', type: 'ay', clue: 'A wide, flat board used to hold, carry, or serve items securely.', sentence: 'The teacher placed scissors and glue on a plastic craft ___.', frequency: 'core' },
    { word: 'Jay', type: 'ay', clue: 'A beautiful, noisy bird known for its brilliant blue feathers.', sentence: 'A bright blue ___ chirped happily from the tree branch.', frequency: 'core' },
    { word: 'Spray', type: 'ay', clue: 'To sprinkle or squirt tiny mist drops of liquid quickly.', sentence: '___ some cool water onto the tropical garden plants.', frequency: 'core' },
    { word: 'Day', type: 'ay', clue: 'The bright time of light between sunrise and the stars coming out.', sentence: 'Every single ___ is a brand new chance to learn and play.', frequency: 'core' },
    { word: 'May', type: 'ay', clue: 'The fifth month of the calendar year, or a polite way to ask permission.', sentence: '___ I please play on the playground swings next?', frequency: 'core' },
    { word: 'Stay', type: 'ay', clue: 'To remain in one stable place instead of leaving.', sentence: 'Samy loves to ___ close to the fresh green lettuce.', frequency: 'core' },
    { word: 'Play', type: 'ay', clue: 'To have fun, play games, explore, or build toys together.', sentence: "Let's assemble a cardboard fort and ___ spaceships inside.", frequency: 'core' },
    { word: 'Gray', type: 'ay', clue: 'A cool color created by mixing bright white and dark black.', sentence: 'When rain clouds gather in the sky, they turn a dark ___.', frequency: 'core' },
    { word: 'Portray', type: 'ay', clue: 'To act as or sketch a character or story to show what they are like.', sentence: 'The children will ___ busy workers in the class play.', isBonus: true },
    { word: 'Dismay', type: 'ay', clue: 'A sudden feeling of disappointment, shock, or sadness.', sentence: 'To our huge ___, the beautiful chocolate cake was dropped.', isBonus: true },
    { word: 'Grape', type: 'bonus', clue: 'A sweet, round purple or green fruit that grows in clusters.', sentence: 'I popped a juicy green ___ straight into my mouth.', isBonus: true },
    { word: 'Drape', type: 'bonus', clue: 'To loosely cover or hang cloth over furniture or windows.', sentence: "Let's ___ the white sheets over the chairs to make a fort.", isBonus: true },
    { word: 'Vapor', type: 'bonus', clue: 'Mist, steam, or tiny water drops floating warm in the air.', sentence: 'Hot water ___ rose slowly from the steaming cocoa mug.', isBonus: true },
    { word: 'Strain', type: 'ai', clue: 'To stretch very tightly, overwork, or separate liquid from solid food.', sentence: 'Use a metal colander to ___ the water from the hot pasta.', isBonus: true },
    { word: 'Constrain', type: 'ai', clue: 'To hold back, limit, or restrict movement or freedom.', sentence: "We shouldn't let tiny cages ___ active wild animals.", isBonus: true },
];
