import React, { useState } from 'react';
import { Calendar, Award, Settings, LogOut, ChevronDown, Sparkles, BrainCircuit, BarChart2, Users, UserCheck } from 'lucide-react';

// Import reusable components
import Card from '../components/common/Card';
import CardHeader from '../components/common/CardHeader';
import Modal from '../components/common/Modal';


export default function Dashboard({ user, onLogout }) {
    const [activeTab, setActiveTab] = useState('dashboard');
    const [modalState, setModalState] = useState({ isOpen: false, title: '', content: '', isLoading: false, contentType: 'text' });
    
    // Mock Data
    const upcomingSessionsData = [{ id: 1, title: 'Calculus Review' }, { id: 2, title: 'Essay Workshop' }];
    const learningProgressData = [{ id: 1, subject: 'Algebra', progress: 85, color: 'bg-blue-500' }, { id: 2, subject: 'Physics', progress: 62, color: 'bg-green-500' }];

    // Gemini API Logic
    const callGemini = async (prompt, responseType) => { /* ... Gemini API call logic ... */ };
    const openModal = (title, prompt, responseType) => {
        setModalState({ isOpen: true, title, content: '', isLoading: true, contentType: responseType });
        // callGemini(prompt, responseType); // Temporarily commented out for codespace
        // Simulate a delay and response for now
        setTimeout(() => {
             const dummyContent = responseType === 'json' ? { questions: [{ question_text: "What is 2+2?", options: ["3", "4", "5"], correct_answer: "4", explanation: "It's math."}] } : "This is a study plan generated by AI.";
             setModalState({ isOpen: true, title, content: dummyContent, isLoading: false, contentType: responseType });
        }, 1500);
    };
    const closeModal = () => setModalState({ isOpen: false, title: '', content: '', isLoading: false });

    const handlePlanWeek = () => openModal("✨ AI Study Plan", `Create a study plan for...`, 'text');
    const handleGenerateQuestions = (subject) => openModal(`✨ Practice: ${subject}`, `Generate questions for...`, 'json');

    // Sub-components for the Dashboard
    const Sidebar = () => {
        const baseNav = [{ id: 'dashboard', label: 'Dashboard', icon: BarChart2 }, { id: 'settings', label: 'Settings', icon: Settings }];
        let navItems = [...baseNav];
        if (user.role === 'tutor') navItems.splice(1, 0, { id: 'students', label: 'My Students', icon: Users });
        if (user.role === 'admin') navItems.push({ id: 'admin-panel', label: 'Admin Panel', icon: UserCheck });
        return (<div className="w-64 bg-white flex flex-col shadow-lg"><div className="p-6 text-center border-b"><h1 className="text-2xl font-bold">StartRight</h1></div><nav className="flex-grow p-4"><ul>{navItems.map(item => (<li key={item.id}><button onClick={() => setActiveTab(item.id)} className={`w-full flex items-center px-4 py-3 my-1 rounded-lg transition-colors ${activeTab === item.id ? 'bg-blue-500 text-white' : 'text-gray-600 hover:bg-gray-100'}`}><item.icon className="w-5 h-5 mr-3" /><span>{item.label}</span></button></li>))}</ul></nav><div className="p-4 border-t"><button onClick={onLogout} className="w-full flex items-center px-4 py-3 rounded-lg text-gray-600 hover:bg-gray-100"><LogOut className="w-5 h-5 mr-3" /><span>Logout</span></button></div></div>);
    };

    const Header = () => (<div className="flex justify-between items-center mb-8"><div><h2 className="text-3xl font-bold">{`Welcome, ${user.name}!`}</h2><p className="text-gray-500">{`Your ${user.role} dashboard.`}</p></div><div className="flex items-center space-x-2"><img src={user.avatar} alt="Avatar" className="w-10 h-10 rounded-full" /><span className="font-semibold">{user.name}</span><ChevronDown className="w-5" /></div></div>);

    const MainDashboardView = () => (
        <div className="space-y-6">
            <Card><CardHeader icon={Calendar} title="Upcoming Sessions" rightContent={<button onClick={handlePlanWeek} className="flex items-center bg-yellow-400 text-gray-800 px-3 py-2 rounded-lg text-sm font-semibold hover:bg-yellow-500"><Sparkles className="w-4 h-4 mr-2" />Plan My Week</button>} /><div className="space-y-3">{upcomingSessionsData.map(s=><div key={s.id} className="flex items-center justify-between bg-gray-50 p-3 rounded-lg"><p className="font-medium">{s.title}</p><button className="bg-blue-500 text-white px-3 py-1 rounded-full text-xs">Join</button></div>)}</div></Card>
            <Card><CardHeader icon={Award} title="Learning Progress" /><div className="grid grid-cols-1 md:grid-cols-2 gap-6">{learningProgressData.map(item => (<div key={item.id} className="p-4 rounded-lg bg-gray-50"><div className="flex justify-between items-baseline mb-1"><span>{item.subject}</span><span className="font-bold">{item.progress}%</span></div><div className="w-full bg-gray-200 h-2.5 rounded-full"><div className={`${item.color} h-2.5 rounded-full`} style={{width: `${item.progress}%`}}></div></div><button onClick={()=>handleGenerateQuestions(item.subject)} className="mt-4 flex items-center text-sm text-blue-600 font-semibold"><BrainCircuit className="w-4 h-4 mr-1"/>Generate Practice</button></div>))}</div></Card>
        </div>
    );
    
    const renderContent = () => {
        switch (activeTab) {
            case 'dashboard': return <MainDashboardView />;
            case 'admin-panel': return <Card><CardHeader icon={UserCheck} title="Admin Panel" /><p>Manage users, view analytics, and configure system settings.</p></Card>;
            case 'students': return <Card><CardHeader icon={Users} title="My Students" /><p>View your student roster and track their progress.</p></Card>;
            case 'settings': return <Card><CardHeader icon={Settings} title="Settings" /><p>Manage your account settings.</p></Card>;
            default: return <p>Select a tab</p>;
        }
    };

    return (<div className="min-h-screen bg-gray-50 font-sans"><div className="flex min-h-screen"><Sidebar /><main className="flex-1 p-8"><Header />{renderContent()}</main></div>{modalState.isOpen && <Modal {...modalState} onClose={closeModal} />}</div>);
};